name: Check PHPUnit Results

on: [ pull_request ]

jobs:
  check-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if phpunit.junit.xml was modified
        id: check_file
        run: |
          if git log -1 --pretty=format: --name-only | grep -q 'test/phpunit.junit'; then
            echo "File phpunit.junit.xml was modified in the last commit."
            echo "file_modified=true" >> $GITHUB_ENV
          else
            echo "File phpunit.junit.xml was NOT modified in the last commit."
            echo "file_modified=false" >> $GITHUB_ENV
            exit 1  # Forcer l'échec si le fichier n'a pas été modifié
          fi

      - name: Check test results
        if: env.file_modified == 'true'
        run: |
          if grep -q 'failures="0"' test/phpunit.junit.xml; then
            echo "All tests passed!"
          else
            echo "Some tests failed."
            exit 1  # Forcer l'échec si des tests ont échoué
          fi

      - name: Fail the workflow if file wasn't modified or tests failed
        if: failure()
        run: |
          echo "The workflow failed due to file modification or test failures."