name: Check PHPUnit Results

on: [ pull_request ]

jobs:
  check-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if phpunit.junit.xml was modified
        id: check_file
        run: |
          echo "Fetching branch: ${{ github.head_ref }}"
          git fetch origin ${{ github.head_ref }}
          echo "Fetched branch: ${{ github.head_ref }}"

          echo "Checking for modifications in phpunit.junit.xml"
          if git diff --name-only origin/${{ github.head_ref }}..HEAD | grep "test/phpunit.junit.xml"; then
            echo "File phpunit.junit.xml was modified."
            echo "file_modified=true" >> $GITHUB_OUTPUT
          else
            echo "File phpunit.junit.xml was NOT modified."
            echo "file_modified=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Check test results
        if: steps.check_file.outputs.file_modified == 'true'
        run: |
          echo "Checking test results in phpunit.junit.xml"
          if grep 'failures="0"' test/phpunit.junit.xml; then
            echo "All tests passed!"
          else
            echo "Some tests failed."
            exit 1
          fi
        shell: bash

      - name: Fail if file not modified
        if: steps.check_file.outputs.file_modified != 'true'
        run: |
          echo "File phpunit.junit.xml was NOT modified in the pull request."
          exit 1
        shell: bash