name: Check PHPUnit Results

on: [ pull_request ]

jobs:
  check-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if phpunit.junit.xml was modified
        id: check_file
        uses: actions/github-script@v4
        with:
          script: |
            const pr = context.payload.pull_request;
            const { data: files } = await github.pulls.listFiles({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pr.number,
            });
            const fileModified = files.some(file => file.filename === 'test/phpunit.junit.xml');
            core.setOutput('file_modified', fileModified.toString());
            console.log(`File modified: ${fileModified}`);
            if (!fileModified) {
              console.log('File phpunit.junit.xml was NOT modified in the pull request.');
            }

      - name: Check test results
        if: steps.check_file.outputs.file_modified == 'true'
        run: |
          if grep -q 'failures="0"' test/phpunit.junit.xml; then
            echo "All tests passed!"
          else
            echo "Some tests failed."
            exit 1
          fi
        shell: bash

      - name: Fail if file not modified
        if: steps.check_file.outputs.file_modified != 'true'
        run: |
          echo "File phpunit.junit.xml was NOT modified in the pull request."
          exit 1
        shell: bash