name: Check PHPUnit Results

on: [ pull_request ]

jobs:
  check-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      - name: Get date of the last commit
        id: get_commit_date
        run: |
          COMMIT_DATE=$(git log -1 --pretty=format:"%ci" | tail -n 1)
          echo "commit_date=$COMMIT_DATE" >> $GITHUB_ENV

      - name: Get date of phpunit.junit.xml
        id: get_file_date
        run: |
          FILE_DATE=$(xmllint --xpath 'string(//testsuites/@generated)' custom/albatross/test/phpunit.junit.xml)
          echo "file_date=$FILE_DATE" >> $GITHUB_ENV

      - name: Compare dates
        run: |
          COMMIT_DATE=$(date -d "${{ env.commit_date }}" +%s)
          FILE_DATE=$(date -d "${{ env.file_date }}" +%s)
          if [ $FILE_DATE -le $COMMIT_DATE ]; then
            echo "The file phpunit.junit.xml is not newer than the last commit."
            exit 1
          else
            echo "The file phpunit.junit.xml is newer than the last commit."
          fi

      - name: Add timestamp to phpunit.junit.xml
        run: |
          TIMESTAMP=$(date +"%Y-%m-%d %H:%M:%S")
          sed -i "s|<testsuites>|<testsuites generated=\"$TIMESTAMP\">|" test/phpunit.junit.xml

      - name: Check test results
        run: |
          if grep -q 'failures="0"' test/phpunit.junit.xml; then
            echo "All tests passed!"
          else
            echo "Some tests failed."
            exit 1
          fi