name: Check PHPUnit Results

on: [ push ]

jobs:
  check-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Check if phpunit.junit.xml was modified
        id: check_file
        run: |
          LAST_COMMIT=$(git rev-parse HEAD)
          PREVIOUS_COMMIT=$(git rev-parse HEAD^)
          if git diff --name-only $PREVIOUS_COMMIT $LAST_COMMIT | grep -q "test/phpunit.junit.xml"; then
            echo "File phpunit.junit.xml was modified in the last commit."
            echo "file_modified=true" >> $GITHUB_OUTPUT
          else
            echo "File phpunit.junit.xml was NOT modified in the last commit."
            echo "file_modified=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Check test results
        if: steps.check_file.outputs.file_modified == 'true'
        run: |
          echo "Checking test results in phpunit.junit.xml"
          if grep -q 'failures="0"' test/phpunit.junit.xml; then
            echo "All tests passed!"
          else
            echo "Some tests failed."
            exit 1
          fi
        shell: bash

      - name: Fail if file not modified
        if: steps.check_file.outputs.file_modified != 'true'
        run: |
          echo "Error: File phpunit.junit.xml was NOT modified in the last commit."
          exit 1
        shell: bash