name: Check PHPUnit Results

on: [ pull_request ]

jobs:
  check-results:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Check if file was modified in the last commit
        id: check_file
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q 'test/phpunit.junit.xml'; then
            echo "file_modified=true" >> $GITHUB_ENV
          else
            echo "file_modified=false" >> $GITHUB_ENV
            exit 1
          fi

      - name: Check test results
        run: |
          if grep -q 'failures="0"' test/phpunit.junit.xml; then
            echo "All tests passed!"
          else
            echo "Some tests failed."
            exit 1
          fi